#1026: Full Feature test coverage of Census Hub - Use Chrome browser …
ONSdigital/dp-frontend-homepage-controller pull request #141
Opened 2022-09-15 15:34 UTC by joegasewicz

### What

The [dp-frontend-homepage-controller](https://github.com/ONSdigital/dp-frontend-homepage-controller "‌") is missing component tests, these need to be added before changing the page or data handled in the controller for Census Hub.

### How to review

pull down the code and run the following:
```
make test-component
```

### Who can review
anyone

Describe who worked on the changes, so that other people can review.
@joegasewicz & @geoffmrb

2022-10-06 16:32 UTC, geoffmrb approved these changes

2022-10-07 14:09 UTC, nshumoogum reviewed
Missing ci files for running component tests on CI/CD pipelines, also spotted a failing component test. Please run again locally again and fix thanks

2022-10-07 14:10 UTC, nshumoogum requested changes
See comments above

2022-10-20 12:51 UTC, joegasewicz commented on features/home_page_component.go
> +		Topic: &top.ClienterMock{
This has been rectified

2022-10-20 12:52 UTC, joegasewicz commented on features/home_page_component.go
> +		ImageAPI: &homepage.ImageClientMock{
This has been rectified

2022-10-20 15:04 UTC, merged